[package]
name = "acteon-state-redis"
description = "Redis state store and distributed lock backend for Acteon"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[features]
default = []
integration = []

[dependencies]
acteon-core = { workspace = true }
acteon-state = { workspace = true }
async-trait = { workspace = true }
deadpool-redis = { workspace = true }
redis = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
uuid = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["test-util"] }

[lints]
workspace = true
