[package]
name = "acteon-audit-clickhouse"
description = "ClickHouse audit store backend for Acteon"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
acteon-audit = { workspace = true }
acteon-core = { workspace = true }
async-trait = { workspace = true }
chrono = { workspace = true }
clickhouse = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

[lints]
workspace = true
